export type RegistrationLanguage = 'it' | 'en' | 'pl' | 'fr' | 'de' | 'es' | 'pt' | 'ko' | 'ja' | 'zh';

export interface RegistrationCopy {
  registrationEyebrow: string; introTitle: string; lawText: string; bookingText: string; pressStart: string; start: string;
  bookingName: string; stay: string; guestCount: string; guestTitle: string; holder: string; companion: string; formHint: string;
  surname: string; name: string; gender: string; male: string; female: string; birthDate: string; nationality: string; residenceCountry: string; residenceHint: string; birthPlace: string; documentType: string; documentNumber: string;
  choose: string; back: string; finish: string; next: string; dateTitle: string; dayPrompt: string; dayPlaceholder: string; monthPrompt: string; yearPrompt: string; yearPlaceholder: string;
  invalidDay: string; monthRequired: string; invalidYear: string; invalidDate: string; countryTitle: string; countrySearch: string; birthPlaceTitle: string; birthPlaceSearch: string; docTypeTitle: string;
  confirm: string; cancel: string; noResults: string; missingTitle: string; missingText: string; ageError: string; completeTitle: string; completeText: string;
  partialTitle: string; partialText: string; firstRequiredTitle: string; firstRequiredText: string; ok: string; registered: string; loading: string;
}

export const REGISTRATION_LOCALES: Record<RegistrationLanguage, string> = {
  it: 'it-IT', en: 'en-US', pl: 'pl-PL', fr: 'fr-FR', de: 'de-DE', es: 'es-ES', pt: 'pt-PT', ko: 'ko-KR', ja: 'ja-JP', zh: 'zh-CN'
};

export const REGISTRATION_COPY: Record<RegistrationLanguage, RegistrationCopy> = {
  it: {
    residenceCountry: "Stato di residenza", residenceHint: "Precompilato dalla nazionalità. Se vivi in un altro Paese, modificalo.",
    registrationEyebrow: 'Registrazione ospiti', introTitle: 'Prepariamo i documenti',
    lawText: 'Per la legge italiana sul turismo è obbligatorio registrare un documento di identità della persona che ha prenotato. Per gli altri componenti bastano i dati anagrafici, purché abbiano più di 10 anni.',
    bookingText: 'Nella tua prenotazione risultano {total} ospiti: dovrai registrare 1 documento di identità e {profiles} schede anagrafiche per gli ospiti con più di 10 anni.', pressStart: 'Premi il pulsante qui sotto per iniziare.', start: 'Inizia', bookingName: 'Prenotazione di', stay: 'Soggiorno', guestCount: 'Ospiti', guestTitle: 'Ospite {current} di {total}', holder: 'Titolare della prenotazione', companion: 'Componente della prenotazione', formHint: 'Inserisci i dati esattamente come riportati sul documento.',
    surname: 'Cognome', name: 'Nome', gender: 'Sesso', male: 'Maschio', female: 'Femmina', birthDate: 'Data di nascita', nationality: 'Nazionalità', birthPlace: 'Comune italiano o stato estero di nascita', documentType: 'Tipo di documento', documentNumber: 'Numero del documento', choose: 'Scegli', back: 'Indietro', finish: 'Ho finito, salva i dati', next: 'Avanti',
    dateTitle: 'Data di nascita', dayPrompt: 'In che giorno sei nato?', dayPlaceholder: 'Giorno, da 1 a 31', monthPrompt: 'In quale mese sei nato?', yearPrompt: 'In quale anno sei nato?', yearPlaceholder: 'Anno a 4 cifre', invalidDay: 'Inserisci un giorno compreso tra 1 e 31.', monthRequired: 'Seleziona il mese di nascita.', invalidYear: 'L’età deve essere maggiore di 10 anni e minore di 110 anni.', invalidDate: 'La data inserita non esiste. Controlla giorno, mese e anno.',
    countryTitle: 'Scegli la nazionalità', countrySearch: 'Scrivi il nome della nazione', birthPlaceTitle: 'Scegli il luogo di nascita', birthPlaceSearch: 'Cerca un comune o uno stato estero', docTypeTitle: 'Scegli il tipo di documento', confirm: 'OK, conferma', cancel: 'Annulla', noResults: 'Nessun risultato trovato', missingTitle: 'Mancano alcune informazioni', missingText: 'Completa questi campi prima di continuare:', ageError: 'La persona deve avere più di 10 anni e meno di 110 anni.', completeTitle: 'Registrazione completata', completeText: 'Ok, hai registrato tutti i dati. Adesso prosegui con gli altri step.', partialTitle: 'Registrazione parziale', partialText: 'Hai registrato solo {registered} ospiti su {total}. Se gli ospiti mancanti hanno meno di 10 anni va bene; in caso contrario potrai completare la registrazione in seguito.', firstRequiredTitle: 'Documento obbligatorio', firstRequiredText: 'Prima di salvare devi completare almeno il documento di identità del primo ospite.', ok: 'OK', registered: 'Registrato', loading: 'Caricamento elenco…'
  },
  en: {
    residenceCountry: "Country of residence", residenceHint: "Prefilled from your nationality. Change it if you live in another country.",
    registrationEyebrow: 'Guest registration', introTitle: 'Let’s prepare the documents', lawText: 'Italian tourism law requires an identity document for the person who made the booking. For the other guests, personal details are sufficient if they are over 10 years old.', bookingText: 'Your booking includes {total} guests: you must register 1 identity document and {profiles} personal-detail forms for guests over 10.', pressStart: 'Press the button below to begin.', start: 'Start', bookingName: 'Booking by', stay: 'Stay', guestCount: 'Guests', guestTitle: 'Guest {current} of {total}', holder: 'Booking holder', companion: 'Booking guest', formHint: 'Enter the details exactly as shown on the document.', surname: 'Surname', name: 'First name', gender: 'Gender', male: 'Male', female: 'Female', birthDate: 'Date of birth', nationality: 'Nationality', birthPlace: 'Italian town or foreign country of birth', documentType: 'Document type', documentNumber: 'Document number', choose: 'Choose', back: 'Back', finish: 'I’m done, save details', next: 'Next', dateTitle: 'Date of birth', dayPrompt: 'What day were you born?', dayPlaceholder: 'Day, from 1 to 31', monthPrompt: 'What month were you born?', yearPrompt: 'What year were you born?', yearPlaceholder: '4-digit year', invalidDay: 'Enter a day between 1 and 31.', monthRequired: 'Select your birth month.', invalidYear: 'Age must be over 10 and under 110.', invalidDate: 'That date does not exist. Check the day, month and year.', countryTitle: 'Choose nationality', countrySearch: 'Type the country name', birthPlaceTitle: 'Choose place of birth', birthPlaceSearch: 'Search for a town or foreign country', docTypeTitle: 'Choose document type', confirm: 'OK, confirm', cancel: 'Cancel', noResults: 'No results found', missingTitle: 'Some information is missing', missingText: 'Complete these fields before continuing:', ageError: 'The person must be over 10 and under 110.', completeTitle: 'Registration complete', completeText: 'Great, you have registered all the details. You can now continue with the other steps.', partialTitle: 'Partial registration', partialText: 'You registered only {registered} of {total} guests. This is fine if the missing guests are under 10; otherwise you can complete registration later.', firstRequiredTitle: 'Document required', firstRequiredText: 'Before saving, you must complete at least the identity document for the first guest.', ok: 'OK', registered: 'Registered', loading: 'Loading list…'
  },
  pl: {
    residenceCountry: "Kraj zamieszkania", residenceHint: "Uzupełniono na podstawie obywatelstwa. Zmień, jeśli mieszkasz w innym kraju.",
    registrationEyebrow: 'Rejestracja gości', introTitle: 'Przygotujmy dokumenty', lawText: 'Włoskie prawo turystyczne wymaga dokumentu tożsamości osoby, która dokonała rezerwacji. W przypadku pozostałych gości wystarczą dane osobowe, jeśli mają więcej niż 10 lat.', bookingText: 'Rezerwacja obejmuje {total} gości: należy zarejestrować 1 dokument tożsamości i {profiles} formularze danych gości powyżej 10 lat.', pressStart: 'Naciśnij przycisk poniżej, aby rozpocząć.', start: 'Zacznij', bookingName: 'Rezerwacja:', stay: 'Pobyt', guestCount: 'Goście', guestTitle: 'Gość {current} z {total}', holder: 'Osoba rezerwująca', companion: 'Uczestnik rezerwacji', formHint: 'Wpisz dane dokładnie tak, jak w dokumencie.', surname: 'Nazwisko', name: 'Imię', gender: 'Płeć', male: 'Mężczyzna', female: 'Kobieta', birthDate: 'Data urodzenia', nationality: 'Narodowość', birthPlace: 'Włoska gmina lub zagraniczne państwo urodzenia', documentType: 'Rodzaj dokumentu', documentNumber: 'Numer dokumentu', choose: 'Wybierz', back: 'Wstecz', finish: 'Zakończ i zapisz dane', next: 'Dalej', dateTitle: 'Data urodzenia', dayPrompt: 'Którego dnia się urodziłeś?', dayPlaceholder: 'Dzień od 1 do 31', monthPrompt: 'W którym miesiącu się urodziłeś?', yearPrompt: 'W którym roku się urodziłeś?', yearPlaceholder: 'Rok, 4 cyfry', invalidDay: 'Wpisz dzień od 1 do 31.', monthRequired: 'Wybierz miesiąc urodzenia.', invalidYear: 'Wiek musi wynosić więcej niż 10 i mniej niż 110 lat.', invalidDate: 'Ta data nie istnieje. Sprawdź dzień, miesiąc i rok.', countryTitle: 'Wybierz narodowość', countrySearch: 'Wpisz nazwę kraju', birthPlaceTitle: 'Wybierz miejsce urodzenia', birthPlaceSearch: 'Szukaj gminy lub obcego państwa', docTypeTitle: 'Wybierz rodzaj dokumentu', confirm: 'OK, potwierdź', cancel: 'Anuluj', noResults: 'Brak wyników', missingTitle: 'Brakuje informacji', missingText: 'Uzupełnij pola przed kontynuacją:', ageError: 'Osoba musi mieć więcej niż 10 i mniej niż 110 lat.', completeTitle: 'Rejestracja zakończona', completeText: 'Wszystkie dane zostały zarejestrowane. Możesz przejść do kolejnych kroków.', partialTitle: 'Częściowa rejestracja', partialText: 'Zarejestrowano tylko {registered} z {total} gości. To wystarczy, jeśli brakujący goście mają mniej niż 10 lat; w przeciwnym razie dane można uzupełnić później.', firstRequiredTitle: 'Wymagany dokument', firstRequiredText: 'Przed zapisaniem uzupełnij dokument tożsamości pierwszego gościa.', ok: 'OK', registered: 'Zarejestrowano', loading: 'Ładowanie listy…'
  },
  fr: {
    residenceCountry: "Pays de résidence", residenceHint: "Prérempli selon votre nationalité. Modifiez-le si vous vivez dans un autre pays.",
    registrationEyebrow: 'Enregistrement des voyageurs', introTitle: 'Préparons les documents', lawText: 'La loi italienne sur le tourisme exige une pièce d’identité de la personne qui a réservé. Pour les autres voyageurs, les données personnelles suffisent s’ils ont plus de 10 ans.', bookingText: 'Votre réservation comprend {total} voyageurs : vous devez enregistrer 1 pièce d’identité et {profiles} fiches personnelles pour les voyageurs de plus de 10 ans.', pressStart: 'Appuyez sur le bouton ci-dessous pour commencer.', start: 'Commencer', bookingName: 'Réservation de', stay: 'Séjour', guestCount: 'Voyageurs', guestTitle: 'Voyageur {current} sur {total}', holder: 'Titulaire de la réservation', companion: 'Voyageur de la réservation', formHint: 'Saisissez les données exactement comme sur le document.', surname: 'Nom', name: 'Prénom', gender: 'Sexe', male: 'Homme', female: 'Femme', birthDate: 'Date de naissance', nationality: 'Nationalité', birthPlace: 'Commune italienne ou pays étranger de naissance', documentType: 'Type de document', documentNumber: 'Numéro du document', choose: 'Choisir', back: 'Retour', finish: 'Terminer et enregistrer', next: 'Suivant', dateTitle: 'Date de naissance', dayPrompt: 'Quel jour êtes-vous né ?', dayPlaceholder: 'Jour, de 1 à 31', monthPrompt: 'Quel mois êtes-vous né ?', yearPrompt: 'Quelle année êtes-vous né ?', yearPlaceholder: 'Année à 4 chiffres', invalidDay: 'Saisissez un jour entre 1 et 31.', monthRequired: 'Sélectionnez le mois de naissance.', invalidYear: 'L’âge doit être supérieur à 10 ans et inférieur à 110 ans.', invalidDate: 'Cette date n’existe pas. Vérifiez le jour, le mois et l’année.', countryTitle: 'Choisissez la nationalité', countrySearch: 'Saisissez le nom du pays', birthPlaceTitle: 'Choisissez le lieu de naissance', birthPlaceSearch: 'Recherchez une commune ou un pays étranger', docTypeTitle: 'Choisissez le type de document', confirm: 'OK, confirmer', cancel: 'Annuler', noResults: 'Aucun résultat', missingTitle: 'Informations manquantes', missingText: 'Complétez ces champs avant de continuer :', ageError: 'La personne doit avoir plus de 10 ans et moins de 110 ans.', completeTitle: 'Enregistrement terminé', completeText: 'Toutes les données sont enregistrées. Vous pouvez maintenant poursuivre les autres étapes.', partialTitle: 'Enregistrement partiel', partialText: 'Vous avez enregistré seulement {registered} voyageurs sur {total}. Cela convient si les voyageurs manquants ont moins de 10 ans ; sinon vous pourrez terminer plus tard.', firstRequiredTitle: 'Document obligatoire', firstRequiredText: 'Avant d’enregistrer, complétez au moins la pièce d’identité du premier voyageur.', ok: 'OK', registered: 'Enregistré', loading: 'Chargement de la liste…'
  },
  de: {
    residenceCountry: "Wohnsitzland", residenceHint: "Anhand der Staatsangehörigkeit vorausgefüllt. Bitte ändern, wenn du in einem anderen Land wohnst.",
    registrationEyebrow: 'Gäste registrieren', introTitle: 'Bereiten wir die Dokumente vor', lawText: 'Nach italienischem Tourismusrecht ist ein Ausweis der buchenden Person erforderlich. Für weitere Gäste genügen die persönlichen Daten, sofern sie älter als 10 Jahre sind.', bookingText: 'Die Buchung umfasst {total} Gäste: Registriere 1 Ausweis und {profiles} Personenformulare für Gäste über 10.', pressStart: 'Drücke unten, um zu beginnen.', start: 'Starten', bookingName: 'Buchung von', stay: 'Aufenthalt', guestCount: 'Gäste', guestTitle: 'Gast {current} von {total}', holder: 'Buchungsinhaber', companion: 'Mitreisender', formHint: 'Gib die Angaben genau wie im Dokument ein.', surname: 'Nachname', name: 'Vorname', gender: 'Geschlecht', male: 'Männlich', female: 'Weiblich', birthDate: 'Geburtsdatum', nationality: 'Nationalität', birthPlace: 'Italienische Gemeinde oder ausländischer Geburtsstaat', documentType: 'Dokumenttyp', documentNumber: 'Dokumentnummer', choose: 'Auswählen', back: 'Zurück', finish: 'Fertig, Daten speichern', next: 'Weiter', dateTitle: 'Geburtsdatum', dayPrompt: 'An welchem Tag wurdest du geboren?', dayPlaceholder: 'Tag, 1 bis 31', monthPrompt: 'In welchem Monat wurdest du geboren?', yearPrompt: 'In welchem Jahr wurdest du geboren?', yearPlaceholder: 'Vierstellige Jahreszahl', invalidDay: 'Gib einen Tag zwischen 1 und 31 ein.', monthRequired: 'Wähle den Geburtsmonat.', invalidYear: 'Das Alter muss über 10 und unter 110 Jahren liegen.', invalidDate: 'Dieses Datum existiert nicht. Prüfe Tag, Monat und Jahr.', countryTitle: 'Nationalität wählen', countrySearch: 'Land eingeben', birthPlaceTitle: 'Geburtsort wählen', birthPlaceSearch: 'Gemeinde oder ausländischen Staat suchen', docTypeTitle: 'Dokumenttyp wählen', confirm: 'OK, bestätigen', cancel: 'Abbrechen', noResults: 'Keine Ergebnisse', missingTitle: 'Angaben fehlen', missingText: 'Fülle diese Felder aus:', ageError: 'Die Person muss älter als 10 und jünger als 110 sein.', completeTitle: 'Registrierung abgeschlossen', completeText: 'Alle Daten wurden registriert. Fahre jetzt mit den weiteren Schritten fort.', partialTitle: 'Teilweise Registrierung', partialText: 'Du hast nur {registered} von {total} Gästen registriert. Das ist in Ordnung, wenn die fehlenden Gäste unter 10 sind; sonst kannst du später ergänzen.', firstRequiredTitle: 'Ausweis erforderlich', firstRequiredText: 'Vor dem Speichern muss mindestens der Ausweis des ersten Gastes vollständig sein.', ok: 'OK', registered: 'Registriert', loading: 'Liste wird geladen…'
  },
  es: {
    residenceCountry: "País de residencia", residenceHint: "Precompletado según tu nacionalidad. Cámbialo si vives en otro país.",
    registrationEyebrow: 'Registro de huéspedes', introTitle: 'Preparemos los documentos', lawText: 'La ley italiana de turismo exige un documento de identidad de la persona que reservó. Para los demás huéspedes bastan los datos personales si tienen más de 10 años.', bookingText: 'Tu reserva incluye {total} huéspedes: debes registrar 1 documento de identidad y {profiles} fichas personales para los mayores de 10 años.', pressStart: 'Pulsa el botón de abajo para empezar.', start: 'Empezar', bookingName: 'Reserva de', stay: 'Estancia', guestCount: 'Huéspedes', guestTitle: 'Huésped {current} de {total}', holder: 'Titular de la reserva', companion: 'Huésped de la reserva', formHint: 'Introduce los datos exactamente como aparecen en el documento.', surname: 'Apellidos', name: 'Nombre', gender: 'Sexo', male: 'Hombre', female: 'Mujer', birthDate: 'Fecha de nacimiento', nationality: 'Nacionalidad', birthPlace: 'Municipio italiano o país extranjero de nacimiento', documentType: 'Tipo de documento', documentNumber: 'Número del documento', choose: 'Elegir', back: 'Atrás', finish: 'Terminar y guardar datos', next: 'Siguiente', dateTitle: 'Fecha de nacimiento', dayPrompt: '¿Qué día naciste?', dayPlaceholder: 'Día, del 1 al 31', monthPrompt: '¿En qué mes naciste?', yearPrompt: '¿En qué año naciste?', yearPlaceholder: 'Año de 4 cifras', invalidDay: 'Introduce un día entre 1 y 31.', monthRequired: 'Selecciona el mes de nacimiento.', invalidYear: 'La edad debe ser mayor de 10 y menor de 110 años.', invalidDate: 'La fecha no existe. Comprueba día, mes y año.', countryTitle: 'Elige la nacionalidad', countrySearch: 'Escribe el nombre del país', birthPlaceTitle: 'Elige el lugar de nacimiento', birthPlaceSearch: 'Busca un municipio o país extranjero', docTypeTitle: 'Elige el tipo de documento', confirm: 'OK, confirmar', cancel: 'Cancelar', noResults: 'Sin resultados', missingTitle: 'Falta información', missingText: 'Completa estos campos antes de continuar:', ageError: 'La persona debe tener más de 10 y menos de 110 años.', completeTitle: 'Registro completado', completeText: 'Has registrado todos los datos. Continúa con los demás pasos.', partialTitle: 'Registro parcial', partialText: 'Solo has registrado {registered} de {total} huéspedes. Está bien si los que faltan tienen menos de 10 años; si no, podrás completar el registro más tarde.', firstRequiredTitle: 'Documento obligatorio', firstRequiredText: 'Antes de guardar debes completar el documento de identidad del primer huésped.', ok: 'OK', registered: 'Registrado', loading: 'Cargando lista…'
  },
  pt: {
    residenceCountry: "País de residência", residenceHint: "Preenchido com base na nacionalidade. Altere se vive noutro país.",
    registrationEyebrow: 'Registo de hóspedes', introTitle: 'Vamos preparar os documentos', lawText: 'A lei italiana do turismo exige um documento de identidade da pessoa que fez a reserva. Para os restantes hóspedes bastam os dados pessoais, desde que tenham mais de 10 anos.', bookingText: 'A reserva inclui {total} hóspedes: deve registar 1 documento de identidade e {profiles} fichas pessoais para hóspedes com mais de 10 anos.', pressStart: 'Prima o botão abaixo para começar.', start: 'Começar', bookingName: 'Reserva de', stay: 'Estadia', guestCount: 'Hóspedes', guestTitle: 'Hóspede {current} de {total}', holder: 'Titular da reserva', companion: 'Hóspede da reserva', formHint: 'Insira os dados exatamente como aparecem no documento.', surname: 'Apelido', name: 'Nome', gender: 'Sexo', male: 'Masculino', female: 'Feminino', birthDate: 'Data de nascimento', nationality: 'Nacionalidade', birthPlace: 'Município italiano ou país estrangeiro de nascimento', documentType: 'Tipo de documento', documentNumber: 'Número do documento', choose: 'Escolher', back: 'Voltar', finish: 'Terminar e guardar dados', next: 'Seguinte', dateTitle: 'Data de nascimento', dayPrompt: 'Em que dia nasceu?', dayPlaceholder: 'Dia, de 1 a 31', monthPrompt: 'Em que mês nasceu?', yearPrompt: 'Em que ano nasceu?', yearPlaceholder: 'Ano com 4 dígitos', invalidDay: 'Insira um dia entre 1 e 31.', monthRequired: 'Selecione o mês de nascimento.', invalidYear: 'A idade deve ser superior a 10 e inferior a 110 anos.', invalidDate: 'A data não existe. Verifique dia, mês e ano.', countryTitle: 'Escolha a nacionalidade', countrySearch: 'Escreva o nome do país', birthPlaceTitle: 'Escolha o local de nascimento', birthPlaceSearch: 'Procure um município ou país estrangeiro', docTypeTitle: 'Escolha o tipo de documento', confirm: 'OK, confirmar', cancel: 'Cancelar', noResults: 'Sem resultados', missingTitle: 'Faltam informações', missingText: 'Preencha estes campos antes de continuar:', ageError: 'A pessoa deve ter mais de 10 e menos de 110 anos.', completeTitle: 'Registo concluído', completeText: 'Registou todos os dados. Continue agora com as outras etapas.', partialTitle: 'Registo parcial', partialText: 'Registou apenas {registered} de {total} hóspedes. Está correto se os hóspedes em falta tiverem menos de 10 anos; caso contrário pode completar mais tarde.', firstRequiredTitle: 'Documento obrigatório', firstRequiredText: 'Antes de guardar, complete pelo menos o documento do primeiro hóspede.', ok: 'OK', registered: 'Registado', loading: 'A carregar lista…'
  },
  ko: {
    residenceCountry: "거주 국가", residenceHint: "국적을 기준으로 자동 입력됩니다. 다른 국가에 거주하면 변경해 주세요.",
    registrationEyebrow: '투숙객 등록', introTitle: '서류를 준비해 주세요', lawText: '이탈리아 관광법에 따라 예약자의 신분증 등록은 필수입니다. 다른 투숙객은 만 10세를 초과한 경우 인적 사항만 등록하면 됩니다.', bookingText: '예약 인원은 {total}명입니다. 신분증 1개와 만 10세 초과 투숙객의 인적 사항 {profiles}건을 등록해 주세요.', pressStart: '아래 버튼을 눌러 시작하세요.', start: '시작', bookingName: '예약자', stay: '숙박 기간', guestCount: '투숙객', guestTitle: '투숙객 {current} / {total}', holder: '예약자', companion: '동반 투숙객', formHint: '서류에 적힌 내용과 동일하게 입력하세요.', surname: '성', name: '이름', gender: '성별', male: '남성', female: '여성', birthDate: '생년월일', nationality: '국적', birthPlace: '출생 이탈리아 도시 또는 외국 국가', documentType: '신분증 종류', documentNumber: '신분증 번호', choose: '선택', back: '이전', finish: '완료 및 저장', next: '다음', dateTitle: '생년월일', dayPrompt: '태어난 날은 며칠인가요?', dayPlaceholder: '1~31 사이의 날짜', monthPrompt: '태어난 달은 언제인가요?', yearPrompt: '태어난 해는 언제인가요?', yearPlaceholder: '연도 4자리', invalidDay: '1에서 31 사이의 날짜를 입력하세요.', monthRequired: '태어난 달을 선택하세요.', invalidYear: '나이는 만 10세 초과 110세 미만이어야 합니다.', invalidDate: '존재하지 않는 날짜입니다. 날짜를 확인하세요.', countryTitle: '국적 선택', countrySearch: '국가 이름 입력', birthPlaceTitle: '출생지 선택', birthPlaceSearch: '이탈리아 도시 또는 외국 국가 검색', docTypeTitle: '신분증 종류 선택', confirm: '확인', cancel: '취소', noResults: '검색 결과 없음', missingTitle: '입력하지 않은 정보가 있습니다', missingText: '계속하기 전에 다음 항목을 입력하세요:', ageError: '만 10세 초과 110세 미만이어야 합니다.', completeTitle: '등록 완료', completeText: '모든 정보를 등록했습니다. 다음 단계로 진행하세요.', partialTitle: '일부 등록 완료', partialText: '총 {total}명 중 {registered}명만 등록했습니다. 미등록 투숙객이 만 10세 이하이면 괜찮으며, 그렇지 않으면 나중에 완료할 수 있습니다.', firstRequiredTitle: '신분증 필수', firstRequiredText: '저장하려면 첫 번째 투숙객의 신분증을 먼저 완료하세요.', ok: '확인', registered: '등록됨', loading: '목록 불러오는 중…'
  },
  ja: {
    residenceCountry: "居住国", residenceHint: "国籍に基づいて自動入力されます。別の国にお住まいの場合は変更してください。",
    registrationEyebrow: '宿泊者登録', introTitle: '書類を準備しましょう', lawText: 'イタリアの観光法により、予約者本人の身分証明書の登録が必要です。その他の宿泊者は、10歳を超えている場合、個人情報のみで登録できます。', bookingText: '予約は{total}名です。身分証明書1件と、10歳を超える宿泊者の個人情報{profiles}件を登録してください。', pressStart: '下のボタンを押して開始してください。', start: '開始', bookingName: '予約者', stay: '宿泊期間', guestCount: '宿泊者', guestTitle: '宿泊者 {current} / {total}', holder: '予約代表者', companion: '同伴宿泊者', formHint: '書類に記載されたとおりに入力してください。', surname: '姓', name: '名', gender: '性別', male: '男性', female: '女性', birthDate: '生年月日', nationality: '国籍', birthPlace: '出生したイタリアの市町村または外国', documentType: '書類の種類', documentNumber: '書類番号', choose: '選択', back: '戻る', finish: '完了して保存', next: '次へ', dateTitle: '生年月日', dayPrompt: '生まれた日は何日ですか？', dayPlaceholder: '1～31の日', monthPrompt: '生まれた月はいつですか？', yearPrompt: '生まれた年はいつですか？', yearPlaceholder: '西暦4桁', invalidDay: '1から31までの日を入力してください。', monthRequired: '生まれた月を選択してください。', invalidYear: '年齢は10歳を超え110歳未満である必要があります。', invalidDate: '存在しない日付です。日・月・年を確認してください。', countryTitle: '国籍を選択', countrySearch: '国名を入力', birthPlaceTitle: '出生地を選択', birthPlaceSearch: 'イタリアの市町村または外国を検索', docTypeTitle: '書類の種類を選択', confirm: '確認', cancel: 'キャンセル', noResults: '結果がありません', missingTitle: '未入力の情報があります', missingText: '続ける前に次の項目を入力してください：', ageError: '年齢は10歳を超え110歳未満である必要があります。', completeTitle: '登録完了', completeText: 'すべての情報を登録しました。次のステップへ進んでください。', partialTitle: '一部登録済み', partialText: '{total}名中{registered}名のみ登録しました。未登録者が10歳以下なら問題ありません。それ以外の場合は後で登録を完了できます。', firstRequiredTitle: '身分証明書が必要です', firstRequiredText: '保存する前に、最初の宿泊者の身分証明書を完了してください。', ok: 'OK', registered: '登録済み', loading: '一覧を読み込み中…'
  },
  zh: {
    residenceCountry: "居住国家", residenceHint: "根据国籍预填。如果您居住在其他国家，请修改。",
    registrationEyebrow: '住客登记', introTitle: '准备登记证件', lawText: '根据意大利旅游法规，预订人的身份证件必须登记。其他年满10周岁的住客只需登记个人资料。', bookingText: '您的预订共有{total}位住客：需要登记1份身份证件，以及{profiles}份年满10周岁住客的个人资料。', pressStart: '请点击下方按钮开始。', start: '开始', bookingName: '预订人', stay: '住宿日期', guestCount: '住客', guestTitle: '住客 {current} / {total}', holder: '预订人', companion: '同行住客', formHint: '请严格按照证件内容填写。', surname: '姓', name: '名', gender: '性别', male: '男', female: '女', birthDate: '出生日期', nationality: '国籍', birthPlace: '出生的意大利市镇或外国国家', documentType: '证件类型', documentNumber: '证件号码', choose: '选择', back: '返回', finish: '完成并保存资料', next: '下一步', dateTitle: '出生日期', dayPrompt: '您是哪一天出生的？', dayPlaceholder: '日期，1至31', monthPrompt: '您出生在哪个月？', yearPrompt: '您出生于哪一年？', yearPlaceholder: '4位年份', invalidDay: '请输入1至31之间的日期。', monthRequired: '请选择出生月份。', invalidYear: '年龄必须大于10岁且小于110岁。', invalidDate: '该日期不存在，请检查日、月和年。', countryTitle: '选择国籍', countrySearch: '输入国家名称', birthPlaceTitle: '选择出生地', birthPlaceSearch: '搜索意大利市镇或外国国家', docTypeTitle: '选择证件类型', confirm: '确定', cancel: '取消', noResults: '未找到结果', missingTitle: '部分信息尚未填写', missingText: '继续前请填写以下项目：', ageError: '年龄必须大于10岁且小于110岁。', completeTitle: '登记完成', completeText: '所有资料已登记。现在可以继续其他步骤。', partialTitle: '部分登记', partialText: '共{total}位住客，仅登记了{registered}位。如果未登记住客不满或等于10岁则没有问题，否则可稍后补充。', firstRequiredTitle: '必须登记证件', firstRequiredText: '保存前请至少完成第一位住客的身份证件登记。', ok: '确定', registered: '已登记', loading: '正在加载列表…'
  }
};
