const labels: Record<string, string[]> = {
  it: ['Caricamento…', 'Aggiorna', 'Impossibile caricare le istruzioni. Riprova.', 'Nessuna istruzione disponibile.', 'Immagine non disponibile.', 'Guarda il video', 'Wi-Fi non disponibile.', 'Nome rete', 'Password', 'Codice non disponibile.', 'Invio comando…', 'Chiudi', 'Comando inviato. Verifica che il portone sia aperto.', 'Dispositivo non disponibile o comando non riuscito.', 'Apertura non consentita in questo periodo.', 'Prenotazione o date non valide.', 'Comando inviato, ma stato dispositivo non aggiornato. Verifica il portone.', 'Esito incerto. Verifica il portone prima di riprovare.', 'Accesso non consentito. Torna alla mappa e verifica gli step precedenti.', 'QR Wi-Fi non disponibile. Usa le credenziali indicate.'],
  en: ['Loading…', 'Refresh', 'Unable to load instructions. Please retry.', 'No instructions available.', 'Image unavailable.', 'Watch video', 'Wi-Fi unavailable.', 'Network name', 'Password', 'Code unavailable.', 'Sending command…', 'Close', 'Command sent. Check whether the door is open.', 'Device unavailable or command failed.', 'Opening is not allowed during this period.', 'Invalid booking or dates.', 'Command sent, but device status was not updated. Check the door.', 'Outcome uncertain. Check the door before trying again.', 'Access denied. Return to the map and check the previous steps.', 'Wi-Fi QR unavailable. Use the credentials shown.'],
  pl: ['Ładowanie…', 'Odśwież', 'Nie można wczytać instrukcji. Spróbuj ponownie.', 'Brak instrukcji.', 'Obraz niedostępny.', 'Obejrzyj film', 'Wi-Fi niedostępne.', 'Nazwa sieci', 'Hasło', 'Kod niedostępny.', 'Wysyłanie polecenia…', 'Zamknij', 'Polecenie wysłane. Sprawdź, czy drzwi są otwarte.', 'Urządzenie niedostępne lub polecenie nie powiodło się.', 'Otwarcie w tym okresie jest niedozwolone.', 'Nieprawidłowa rezerwacja lub daty.', 'Polecenie wysłane, ale status urządzenia nie został zaktualizowany. Sprawdź drzwi.', 'Wynik niepewny. Sprawdź drzwi przed ponowną próbą.', 'Brak dostępu. Wróć do mapy i sprawdź poprzednie kroki.', 'Kod QR Wi-Fi niedostępny. Użyj podanych danych.'],
  fr: ['Chargement…', 'Actualiser', 'Impossible de charger les instructions. Réessayez.', 'Aucune instruction disponible.', 'Image indisponible.', 'Voir la vidéo', 'Wi-Fi indisponible.', 'Nom du réseau', 'Mot de passe', 'Code indisponible.', 'Envoi de la commande…', 'Fermer', 'Commande envoyée. Vérifiez si la porte est ouverte.', 'Appareil indisponible ou échec de la commande.', 'Ouverture non autorisée à cette période.', 'Réservation ou dates non valides.', 'Commande envoyée, mais état de l’appareil non actualisé. Vérifiez la porte.', 'Résultat incertain. Vérifiez la porte avant de réessayer.', 'Accès refusé. Revenez au parcours et vérifiez les étapes précédentes.', 'QR Wi-Fi indisponible. Utilisez les identifiants affichés.'],
  de: ['Wird geladen…', 'Aktualisieren', 'Anweisungen konnten nicht geladen werden. Erneut versuchen.', 'Keine Anweisungen verfügbar.', 'Bild nicht verfügbar.', 'Video ansehen', 'WLAN nicht verfügbar.', 'Netzwerkname', 'Passwort', 'Code nicht verfügbar.', 'Befehl wird gesendet…', 'Schließen', 'Befehl gesendet. Prüfen Sie, ob die Tür offen ist.', 'Gerät nicht verfügbar oder Befehl fehlgeschlagen.', 'Öffnen ist in diesem Zeitraum nicht erlaubt.', 'Ungültige Buchung oder Reisedaten.', 'Befehl gesendet, Gerätestatus aber nicht aktualisiert. Prüfen Sie die Tür.', 'Ergebnis ungewiss. Prüfen Sie die Tür vor einem erneuten Versuch.', 'Zugriff verweigert. Zurück zur Übersicht und vorherige Schritte prüfen.', 'WLAN-QR nicht verfügbar. Verwenden Sie die angezeigten Zugangsdaten.'],
  es: ['Cargando…', 'Actualizar', 'No se pudieron cargar las instrucciones. Inténtalo de nuevo.', 'No hay instrucciones disponibles.', 'Imagen no disponible.', 'Ver vídeo', 'Wi-Fi no disponible.', 'Nombre de red', 'Contraseña', 'Código no disponible.', 'Enviando comando…', 'Cerrar', 'Comando enviado. Comprueba si la puerta está abierta.', 'Dispositivo no disponible o comando fallido.', 'No se permite abrir durante este período.', 'Reserva o fechas no válidas.', 'Comando enviado, pero el estado del dispositivo no se actualizó. Comprueba la puerta.', 'Resultado incierto. Comprueba la puerta antes de reintentar.', 'Acceso denegado. Vuelve al mapa y revisa los pasos anteriores.', 'QR Wi-Fi no disponible. Usa las credenciales indicadas.'],
  pt: ['A carregar…', 'Atualizar', 'Não foi possível carregar as instruções. Tente novamente.', 'Sem instruções disponíveis.', 'Imagem indisponível.', 'Ver vídeo', 'Wi-Fi indisponível.', 'Nome da rede', 'Palavra-passe', 'Código indisponível.', 'A enviar comando…', 'Fechar', 'Comando enviado. Verifique se a porta está aberta.', 'Dispositivo indisponível ou comando falhou.', 'A abertura não é permitida neste período.', 'Reserva ou datas inválidas.', 'Comando enviado, mas o estado do dispositivo não foi atualizado. Verifique a porta.', 'Resultado incerto. Verifique a porta antes de tentar novamente.', 'Acesso negado. Volte ao mapa e verifique os passos anteriores.', 'QR Wi-Fi indisponível. Use as credenciais indicadas.'],
  ko: ['불러오는 중…', '새로고침', '안내를 불러올 수 없습니다. 다시 시도하세요.', '안내가 없습니다.', '이미지를 사용할 수 없습니다.', '동영상 보기', 'Wi-Fi를 사용할 수 없습니다.', '네트워크 이름', '비밀번호', '코드를 사용할 수 없습니다.', '명령 전송 중…', '닫기', '명령을 전송했습니다. 문이 열렸는지 확인하세요.', '장치를 사용할 수 없거나 명령이 실패했습니다.', '이 기간에는 문을 열 수 없습니다.', '예약 또는 날짜가 유효하지 않습니다.', '명령을 전송했지만 장치 상태를 갱신하지 못했습니다. 문을 확인하세요.', '결과가 불확실합니다. 다시 시도하기 전에 문을 확인하세요.', '접근이 거부되었습니다. 지도로 돌아가 이전 단계를 확인하세요.', 'Wi-Fi QR을 사용할 수 없습니다. 표시된 정보를 사용하세요.'],
  ja: ['読み込み中…', '更新', '案内を読み込めません。再試行してください。', '案内はありません。', '画像を表示できません。', '動画を見る', 'Wi-Fiを利用できません。', 'ネットワーク名', 'パスワード', 'コードを表示できません。', 'コマンド送信中…', '閉じる', 'コマンドを送信しました。ドアが開いたか確認してください。', '機器を利用できないか、コマンドが失敗しました。', 'この期間は開錠できません。', '予約または日付が無効です。', 'コマンドを送信しましたが、機器の状態を更新できませんでした。ドアを確認してください。', '結果が不明です。再試行する前にドアを確認してください。', 'アクセスできません。マップに戻り、前のステップを確認してください。', 'Wi-Fi QRを表示できません。表示された接続情報を使用してください。'],
  zh: ['正在加载…', '刷新', '无法加载说明，请重试。', '暂无说明。', '图片不可用。', '观看视频', 'Wi-Fi不可用。', '网络名称', '密码', '代码不可用。', '正在发送指令…', '关闭', '指令已发送，请检查门是否已打开。', '设备不可用或指令失败。', '此时间段不允许开门。', '预订或日期无效。', '指令已发送，但未更新设备状态，请检查门。', '结果不确定，请先检查门再重试。', '访问被拒绝，请返回地图检查前面的步骤。', 'Wi-Fi二维码不可用，请使用显示的凭据。']
};
export function postCopy(language: string) {
  const v = labels[language] ?? labels['it'];
  return { loading:v[0], refresh:v[1], error:v[2], empty:v[3], imageError:v[4], video:v[5], wifiMissing:v[6], ssid:v[7], password:v[8], codeMissing:v[9], sending:v[10], close:v[11], sent:v[12], failed:v[13], period:v[14], booking:v[15], status:v[16], uncertain:v[17], denied:v[18], qrError:v[19] };
}
